name: Urban Rider Society
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a52833'
    - '#040608'
    - '#cd888e'
    - '#67696a'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.9175962628796697
purpose: []
